version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"