/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FetchTranslatedTagsParams,
  HTTPValidationError,
  Tag,
  TagFlagUpdate
} from '.././model';

import { customAxios } from '.././custom-axios';




/**
 * 翻訳済みのタグ一覧を取得するエンドポイント。

- 指定した言語（例: `"ja"` や `"en"`）に対応したタグを返します。
- 使用用途：多言語対応のフロントエンド表示など。

### クエリパラメータ:
- `language` (str): 翻訳対象の言語コード（デフォルト: `"ja"`）

### レスポンス:
- `200 OK`: 成功時に翻訳済みタグの配列を返します
- `404 Not Found`: タグが存在しない場合
- `500 Internal Server Error`: サーバ内部でエラーが発生した場合
 * @summary Fetch Translated Tags
 */
export const fetchTranslatedTags = (
    params?: FetchTranslatedTagsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<Tag[]>(
      {url: `/tag/list`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchTranslatedTagsQueryKey = (params?: FetchTranslatedTagsParams,) => {
    return [`/tag/list`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchTranslatedTagsQueryOptions = <TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = HTTPValidationError>(params?: FetchTranslatedTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchTranslatedTagsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchTranslatedTags>>> = ({ signal }) => fetchTranslatedTags(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchTranslatedTagsQueryResult = NonNullable<Awaited<ReturnType<typeof fetchTranslatedTags>>>
export type FetchTranslatedTagsQueryError = HTTPValidationError


export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = HTTPValidationError>(
 params: undefined |  FetchTranslatedTagsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchTranslatedTags>>,
          TError,
          Awaited<ReturnType<typeof fetchTranslatedTags>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = HTTPValidationError>(
 params?: FetchTranslatedTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchTranslatedTags>>,
          TError,
          Awaited<ReturnType<typeof fetchTranslatedTags>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = HTTPValidationError>(
 params?: FetchTranslatedTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Translated Tags
 */

export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = HTTPValidationError>(
 params?: FetchTranslatedTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchTranslatedTagsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * タグのお気に入りまたはセンシティブフラグをオン/オフします。

### パスパラメータ:
- `tag_id` (int): フラグを変更する対象のタグID

### リクエストボディ:
- `flag` (str): `"favorite"` もしくは `"sensitive"`
- `value` (bool): `true` でオン、`false` でオフ

### レスポンス:
- `200 OK`: 更新されたタグ情報
- `400 Bad Request`: 不正なフラグ指定
- `404 Not Found`: 指定IDのタグが存在しない
 * @summary Toggle Tag Flag
 */
export const toggleTagFlag = (
    tagId: number,
    tagFlagUpdate: TagFlagUpdate,
 ) => {
      
      
      return customAxios<Tag>(
      {url: `/tag/${tagId}/toggle_flag`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: tagFlagUpdate
    },
      );
    }
  


export const getToggleTagFlagMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleTagFlag>>, TError,{tagId: number;data: TagFlagUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof toggleTagFlag>>, TError,{tagId: number;data: TagFlagUpdate}, TContext> => {

const mutationKey = ['toggleTagFlag'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleTagFlag>>, {tagId: number;data: TagFlagUpdate}> = (props) => {
          const {tagId,data} = props ?? {};

          return  toggleTagFlag(tagId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ToggleTagFlagMutationResult = NonNullable<Awaited<ReturnType<typeof toggleTagFlag>>>
    export type ToggleTagFlagMutationBody = TagFlagUpdate
    export type ToggleTagFlagMutationError = HTTPValidationError

    /**
 * @summary Toggle Tag Flag
 */
export const useToggleTagFlag = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleTagFlag>>, TError,{tagId: number;data: TagFlagUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleTagFlag>>,
        TError,
        {tagId: number;data: TagFlagUpdate},
        TContext
      > => {

      const mutationOptions = getToggleTagFlagMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    