/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyRegisterFavoriteImage,
  FetchFilteredThumnailImagesParams,
  FetchOriginalImageParams,
  FetchSimilarImagesParams,
  HTTPValidationError,
  OriginalImage,
  ThumbnailImage
} from '.././model';

import { customAxios } from '.././custom-axios';




/**
 * 指定された条件に基づいて、画像のサムネイル一覧を取得します。

- `include_sensitive`: センシティブな画像（NSFWなど）も含めるかどうかを指定します（デフォルト: False）。
- `favorites_only`: お気に入りに登録された画像のみを対象とするかを指定します（デフォルト: False）。
- `selected_tag`: 特定のタグに紐づいた画像のみを対象とする場合に指定します。
- `exclude_in_folder`: フォルダに含まれる画像を除外するかどうかを指定します（デフォルト: True）。
- `shuffle`: 取得したサムネイルをランダムにシャッフルするかどうかを指定します（デフォルト: False）。

取得に失敗した場合は、適切なエラーメッセージとステータスコードを返します。
 * @summary Fetch Filtered Thumnail Images
 */
export const fetchFilteredThumnailImages = (
    params?: FetchFilteredThumnailImagesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<ThumbnailImage[]>(
      {url: `/image/thumbnails`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchFilteredThumnailImagesQueryKey = (params?: FetchFilteredThumnailImagesParams,) => {
    return [`/image/thumbnails`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchFilteredThumnailImagesQueryOptions = <TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchFilteredThumnailImagesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>> = ({ signal }) => fetchFilteredThumnailImages(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchFilteredThumnailImagesQueryResult = NonNullable<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>>
export type FetchFilteredThumnailImagesQueryError = HTTPValidationError


export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params: undefined |  FetchFilteredThumnailImagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>,
          TError,
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>,
          TError,
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Filtered Thumnail Images
 */

export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchFilteredThumnailImagesQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * 指定された画像IDに対応するオリジナル画像をBase64形式で取得します。

- `id`: オリジナル画像ファイルのidを指定します。

対応形式は `.png`, `.jpg`, `.jpeg`, `.webp` のみです。

### エラー
- 404: 指定された画像ファイルが存在しない場合
- 400: 対応していない画像形式の場合
- 500: その他の内部エラー
 * @summary Fetch Original Image
 */
export const fetchOriginalImage = (
    params: FetchOriginalImageParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<OriginalImage>(
      {url: `/image/original`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchOriginalImageQueryKey = (params: FetchOriginalImageParams,) => {
    return [`/image/original`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchOriginalImageQueryOptions = <TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchOriginalImageQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchOriginalImage>>> = ({ signal }) => fetchOriginalImage(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchOriginalImageQueryResult = NonNullable<Awaited<ReturnType<typeof fetchOriginalImage>>>
export type FetchOriginalImageQueryError = HTTPValidationError


export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchOriginalImage>>,
          TError,
          Awaited<ReturnType<typeof fetchOriginalImage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchOriginalImage>>,
          TError,
          Awaited<ReturnType<typeof fetchOriginalImage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Original Image
 */

export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchOriginalImageQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * 指定された画像IDをお気に入りとして登録します。

- `image_id`: お気に入り登録対象の画像IDを指定します。

成功時はステータス200を返します。
 * @summary Register Favorite Image
 */
export const registerFavoriteImage = (
    bodyRegisterFavoriteImage: BodyRegisterFavoriteImage,
 signal?: AbortSignal
) => {
      
      
      return customAxios<unknown>(
      {url: `/image/favorite`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bodyRegisterFavoriteImage, signal
    },
      );
    }
  


export const getRegisterFavoriteImageMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerFavoriteImage>>, TError,{data: BodyRegisterFavoriteImage}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof registerFavoriteImage>>, TError,{data: BodyRegisterFavoriteImage}, TContext> => {

const mutationKey = ['registerFavoriteImage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerFavoriteImage>>, {data: BodyRegisterFavoriteImage}> = (props) => {
          const {data} = props ?? {};

          return  registerFavoriteImage(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterFavoriteImageMutationResult = NonNullable<Awaited<ReturnType<typeof registerFavoriteImage>>>
    export type RegisterFavoriteImageMutationBody = BodyRegisterFavoriteImage
    export type RegisterFavoriteImageMutationError = HTTPValidationError

    /**
 * @summary Register Favorite Image
 */
export const useRegisterFavoriteImage = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerFavoriteImage>>, TError,{data: BodyRegisterFavoriteImage}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerFavoriteImage>>,
        TError,
        {data: BodyRegisterFavoriteImage},
        TContext
      > => {

      const mutationOptions = getRegisterFavoriteImageMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * 指定された画像IDに対応する画像を削除します。

- `image_id`: 削除対象の画像IDを指定します。

### 成功時
- ステータス200（削除成功）

### 失敗時
- 404: 対象画像が存在しない
- 500: その他の削除処理中のエラー
 * @summary Delete Image
 */
export const deleteImage = (
    imageId: number,
 ) => {
      
      
      return customAxios<unknown>(
      {url: `/image/${imageId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteImageMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteImage>>, TError,{imageId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteImage>>, TError,{imageId: number}, TContext> => {

const mutationKey = ['deleteImage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteImage>>, {imageId: number}> = (props) => {
          const {imageId} = props ?? {};

          return  deleteImage(imageId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteImageMutationResult = NonNullable<Awaited<ReturnType<typeof deleteImage>>>
    
    export type DeleteImageMutationError = HTTPValidationError

    /**
 * @summary Delete Image
 */
export const useDeleteImage = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteImage>>, TError,{imageId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteImage>>,
        TError,
        {imageId: number},
        TContext
      > => {

      const mutationOptions = getDeleteImageMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * 指定された画像IDに基づいて、類似画像のサムネイル一覧を取得します。

- `image_id`: 類似画像検索の基準となる画像のIDを指定します。
- `show_sensitive`: センシティブな画像（NSFWなど）を含めるかどうかを指定します（True で含める）。
- `top_k`: 類似度が高い上位K件の画像を取得します（デフォルト: 20）。

類似度の計算には、事前に保存された埋め込みベクトルを使用し、コサイン類似度に基づいて類似画像を検索します。
センシティブ画像の除外も埋め込み検索対象からフィルタリングされます。

### レスポンス
- `200 OK`: 類似画像のサムネイル情報のリスト（`ThumbnailImage`）を返します。

### エラー
- `404 Not Found`: 指定された画像に埋め込みベクトルが存在しないか、該当する画像が見つからない場合。
- `500 Internal Server Error`: 類似画像の検索処理中にエラーが発生した場合。
 * @summary Fetch Similar Images
 */
export const fetchSimilarImages = (
    params: FetchSimilarImagesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<ThumbnailImage[]>(
      {url: `/image/similar`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchSimilarImagesQueryKey = (params: FetchSimilarImagesParams,) => {
    return [`/image/similar`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchSimilarImagesQueryOptions = <TData = Awaited<ReturnType<typeof fetchSimilarImages>>, TError = HTTPValidationError>(params: FetchSimilarImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchSimilarImagesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchSimilarImages>>> = ({ signal }) => fetchSimilarImages(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchSimilarImagesQueryResult = NonNullable<Awaited<ReturnType<typeof fetchSimilarImages>>>
export type FetchSimilarImagesQueryError = HTTPValidationError


export function useFetchSimilarImages<TData = Awaited<ReturnType<typeof fetchSimilarImages>>, TError = HTTPValidationError>(
 params: FetchSimilarImagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchSimilarImages>>,
          TError,
          Awaited<ReturnType<typeof fetchSimilarImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchSimilarImages<TData = Awaited<ReturnType<typeof fetchSimilarImages>>, TError = HTTPValidationError>(
 params: FetchSimilarImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchSimilarImages>>,
          TError,
          Awaited<ReturnType<typeof fetchSimilarImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchSimilarImages<TData = Awaited<ReturnType<typeof fetchSimilarImages>>, TError = HTTPValidationError>(
 params: FetchSimilarImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Similar Images
 */

export function useFetchSimilarImages<TData = Awaited<ReturnType<typeof fetchSimilarImages>>, TError = HTTPValidationError>(
 params: FetchSimilarImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchSimilarImagesQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



