/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type FetchTranslatedTagsParams = {
/**
 * 翻訳対象の言語コード（例: 'ja', 'en'）
 */
language?: string;
};
