/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type FetchSimilarImagesParams = {
image_id: number;
show_sensitive: boolean;
top_k?: number;
};
