/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ThumbnailImage } from './thumbnailImage';

export interface FolderInfo {
  id: number;
  name: string;
  description: string;
  thumbnail_images: ThumbnailImage[];
}
