/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type GetItemsApiItemListGetParams = {
/**
 * @minimum 1
 * @maximum 1000
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
orderBy?: string | null;
keyword?: string | null;
ext?: string | null;
tags?: string | null;
folders?: string | null;
};
