/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { OriginalImage } from './originalImage';

export interface OriginalImageResponse {
  status?: string;
  data: OriginalImage[];
}
