/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { OriginalImageImage } from './originalImageImage';
import type { OriginalImageError } from './originalImageError';

export interface OriginalImage {
  id: string;
  image?: OriginalImageImage;
  error?: OriginalImageError;
}
