/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TagCategory } from './tagCategory';
import type { TagGenre } from './tagGenre';

export interface Tag {
  tag_id: number;
  tag_name: string;
  category?: TagCategory;
  genre?: TagGenre;
  is_sensitive?: boolean;
  is_favorite?: boolean;
}
