/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */

export type TagFlag = typeof TagFlag[keyof typeof TagFlag];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TagFlag = {
  favorite: 'favorite',
  sensitive: 'sensitive',
} as const;
