/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { TagsCategory } from './tagsCategory';
import type { TagsGenre } from './tagsGenre';

export interface Tags {
  tag_id: number;
  tag_name: string;
  category?: TagsCategory;
  genre?: TagsGenre;
}
