/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import type { ThumbnailImageThumbnail } from './thumbnailImageThumbnail';

export interface ThumbnailImage {
  id: string;
  thumbnail?: ThumbnailImageThumbnail;
}
