/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BodyDeleteImage,
  BodyRegisterFavoriteImage,
  FetchFilteredThumnailImagesParams,
  FetchOriginalImageParams,
  FetchSimilarImagesParams,
  FetchTranslatedTagsParams,
  FolderCreateRequest,
  FolderInfo,
  HTTPValidationError,
  OriginalImage,
  Tag,
  TagFlagUpdate,
  ThumbnailImage
} from '.././model';

import { customAxios } from '.././custom-axios';




/**
 * 指定された条件に基づいて、画像のサムネイル一覧を取得します。

- `include_sensitive`: センシティブな画像（NSFWなど）も含めるかどうかを指定します（デフォルト: False）。
- `favorites_only`: お気に入りに登録された画像のみを対象とするかを指定します（デフォルト: False）。
- `selected_tag`: 特定のタグに紐づいた画像のみを対象とする場合に指定します。

取得に失敗した場合は、適切なエラーメッセージとステータスコードを返します。
 * @summary Fetch Filtered Thumnail Images
 */
export const fetchFilteredThumnailImages = (
    params?: FetchFilteredThumnailImagesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<ThumbnailImage[]>(
      {url: `/image/thumbnails`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchFilteredThumnailImagesQueryKey = (params?: FetchFilteredThumnailImagesParams,) => {
    return [`/image/thumbnails`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchFilteredThumnailImagesQueryOptions = <TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchFilteredThumnailImagesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>> = ({ signal }) => fetchFilteredThumnailImages(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchFilteredThumnailImagesQueryResult = NonNullable<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>>
export type FetchFilteredThumnailImagesQueryError = HTTPValidationError


export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params: undefined |  FetchFilteredThumnailImagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>,
          TError,
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>,
          TError,
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Filtered Thumnail Images
 */

export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchFilteredThumnailImagesQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * 指定された画像IDに対応するオリジナル画像をBase64形式で取得します。

- `id`: オリジナル画像ファイルのidを指定します。

対応形式は `.png`, `.jpg`, `.jpeg`, `.webp` のみです。

### エラー
- 404: 指定された画像ファイルが存在しない場合
- 400: 対応していない画像形式の場合
- 500: その他の内部エラー
 * @summary Fetch Original Image
 */
export const fetchOriginalImage = (
    params: FetchOriginalImageParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<OriginalImage>(
      {url: `/image/original`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchOriginalImageQueryKey = (params: FetchOriginalImageParams,) => {
    return [`/image/original`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchOriginalImageQueryOptions = <TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchOriginalImageQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchOriginalImage>>> = ({ signal }) => fetchOriginalImage(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchOriginalImageQueryResult = NonNullable<Awaited<ReturnType<typeof fetchOriginalImage>>>
export type FetchOriginalImageQueryError = HTTPValidationError


export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchOriginalImage>>,
          TError,
          Awaited<ReturnType<typeof fetchOriginalImage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchOriginalImage>>,
          TError,
          Awaited<ReturnType<typeof fetchOriginalImage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Original Image
 */

export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchOriginalImageQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * 指定された画像IDをお気に入りとして登録します。

- `image_id`: お気に入り登録対象の画像IDを指定します。

成功時はステータス200を返します。
 * @summary Register Favorite Image
 */
export const registerFavoriteImage = (
    bodyRegisterFavoriteImage: BodyRegisterFavoriteImage,
 signal?: AbortSignal
) => {
      
      
      return customAxios<unknown>(
      {url: `/image/favorite`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bodyRegisterFavoriteImage, signal
    },
      );
    }
  


export const getRegisterFavoriteImageMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerFavoriteImage>>, TError,{data: BodyRegisterFavoriteImage}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof registerFavoriteImage>>, TError,{data: BodyRegisterFavoriteImage}, TContext> => {

const mutationKey = ['registerFavoriteImage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerFavoriteImage>>, {data: BodyRegisterFavoriteImage}> = (props) => {
          const {data} = props ?? {};

          return  registerFavoriteImage(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterFavoriteImageMutationResult = NonNullable<Awaited<ReturnType<typeof registerFavoriteImage>>>
    export type RegisterFavoriteImageMutationBody = BodyRegisterFavoriteImage
    export type RegisterFavoriteImageMutationError = HTTPValidationError

    /**
 * @summary Register Favorite Image
 */
export const useRegisterFavoriteImage = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof registerFavoriteImage>>, TError,{data: BodyRegisterFavoriteImage}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof registerFavoriteImage>>,
        TError,
        {data: BodyRegisterFavoriteImage},
        TContext
      > => {

      const mutationOptions = getRegisterFavoriteImageMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * 指定された画像IDに対応する画像を削除します。

- `image_id`: 削除対象の画像IDを指定します。

### 成功時
- ステータス200（削除成功）

### 失敗時
- 404: 対象画像が存在しない
- 500: その他の削除処理中のエラー
 * @summary Delete Image
 */
export const deleteImage = (
    bodyDeleteImage: BodyDeleteImage,
 ) => {
      
      
      return customAxios<unknown>(
      {url: `/image`, method: 'DELETE',
      headers: {'Content-Type': 'application/json', },
      data: bodyDeleteImage
    },
      );
    }
  


export const getDeleteImageMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteImage>>, TError,{data: BodyDeleteImage}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteImage>>, TError,{data: BodyDeleteImage}, TContext> => {

const mutationKey = ['deleteImage'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteImage>>, {data: BodyDeleteImage}> = (props) => {
          const {data} = props ?? {};

          return  deleteImage(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteImageMutationResult = NonNullable<Awaited<ReturnType<typeof deleteImage>>>
    export type DeleteImageMutationBody = BodyDeleteImage
    export type DeleteImageMutationError = HTTPValidationError

    /**
 * @summary Delete Image
 */
export const useDeleteImage = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteImage>>, TError,{data: BodyDeleteImage}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteImage>>,
        TError,
        {data: BodyDeleteImage},
        TContext
      > => {

      const mutationOptions = getDeleteImageMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * 指定された画像IDに基づいて、類似画像のサムネイル一覧を取得します。

- `image_id`: 類似画像検索の基準となる画像のIDを指定します。
- `show_sensitive`: センシティブな画像（NSFWなど）を含めるかどうかを指定します（True で含める）。
- `top_k`: 類似度が高い上位K件の画像を取得します（デフォルト: 20）。

類似度の計算には、事前に保存された埋め込みベクトルを使用し、コサイン類似度に基づいて類似画像を検索します。
センシティブ画像の除外も埋め込み検索対象からフィルタリングされます。

### レスポンス
- `200 OK`: 類似画像のサムネイル情報のリスト（`ThumbnailImage`）を返します。

### エラー
- `404 Not Found`: 指定された画像に埋め込みベクトルが存在しないか、該当する画像が見つからない場合。
- `500 Internal Server Error`: 類似画像の検索処理中にエラーが発生した場合。
 * @summary Fetch Similar Images
 */
export const fetchSimilarImages = (
    params: FetchSimilarImagesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<ThumbnailImage[]>(
      {url: `/image/similar`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchSimilarImagesQueryKey = (params: FetchSimilarImagesParams,) => {
    return [`/image/similar`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchSimilarImagesQueryOptions = <TData = Awaited<ReturnType<typeof fetchSimilarImages>>, TError = HTTPValidationError>(params: FetchSimilarImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchSimilarImagesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchSimilarImages>>> = ({ signal }) => fetchSimilarImages(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchSimilarImagesQueryResult = NonNullable<Awaited<ReturnType<typeof fetchSimilarImages>>>
export type FetchSimilarImagesQueryError = HTTPValidationError


export function useFetchSimilarImages<TData = Awaited<ReturnType<typeof fetchSimilarImages>>, TError = HTTPValidationError>(
 params: FetchSimilarImagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchSimilarImages>>,
          TError,
          Awaited<ReturnType<typeof fetchSimilarImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchSimilarImages<TData = Awaited<ReturnType<typeof fetchSimilarImages>>, TError = HTTPValidationError>(
 params: FetchSimilarImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchSimilarImages>>,
          TError,
          Awaited<ReturnType<typeof fetchSimilarImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchSimilarImages<TData = Awaited<ReturnType<typeof fetchSimilarImages>>, TError = HTTPValidationError>(
 params: FetchSimilarImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Similar Images
 */

export function useFetchSimilarImages<TData = Awaited<ReturnType<typeof fetchSimilarImages>>, TError = HTTPValidationError>(
 params: FetchSimilarImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchSimilarImages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchSimilarImagesQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 全フォルダ情報を取得
 */
export const fetchAllFolders = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxios<FolderInfo[]>(
      {url: `/folder`, method: 'GET', signal
    },
      );
    }
  

export const getFetchAllFoldersQueryKey = () => {
    return [`/folder`] as const;
    }

    
export const getFetchAllFoldersQueryOptions = <TData = Awaited<ReturnType<typeof fetchAllFolders>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchAllFoldersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchAllFolders>>> = ({ signal }) => fetchAllFolders(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchAllFoldersQueryResult = NonNullable<Awaited<ReturnType<typeof fetchAllFolders>>>
export type FetchAllFoldersQueryError = unknown


export function useFetchAllFolders<TData = Awaited<ReturnType<typeof fetchAllFolders>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchAllFolders>>,
          TError,
          Awaited<ReturnType<typeof fetchAllFolders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchAllFolders<TData = Awaited<ReturnType<typeof fetchAllFolders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchAllFolders>>,
          TError,
          Awaited<ReturnType<typeof fetchAllFolders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchAllFolders<TData = Awaited<ReturnType<typeof fetchAllFolders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 全フォルダ情報を取得
 */

export function useFetchAllFolders<TData = Awaited<ReturnType<typeof fetchAllFolders>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchAllFoldersQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 画像フォルダの作成とサムネイル取得
 */
export const createImageFolder = (
    folderCreateRequest: FolderCreateRequest,
 signal?: AbortSignal
) => {
      
      
      return customAxios<unknown>(
      {url: `/folder`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: folderCreateRequest, signal
    },
      );
    }
  


export const getCreateImageFolderMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createImageFolder>>, TError,{data: FolderCreateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createImageFolder>>, TError,{data: FolderCreateRequest}, TContext> => {

const mutationKey = ['createImageFolder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createImageFolder>>, {data: FolderCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createImageFolder(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateImageFolderMutationResult = NonNullable<Awaited<ReturnType<typeof createImageFolder>>>
    export type CreateImageFolderMutationBody = FolderCreateRequest
    export type CreateImageFolderMutationError = HTTPValidationError

    /**
 * @summary 画像フォルダの作成とサムネイル取得
 */
export const useCreateImageFolder = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createImageFolder>>, TError,{data: FolderCreateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createImageFolder>>,
        TError,
        {data: FolderCreateRequest},
        TContext
      > => {

      const mutationOptions = getCreateImageFolderMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary フォルダ内の画像順序を更新
 */
export const updateFolderOrder = (
    folderId: number,
    updateFolderOrderBody: number[],
 ) => {
      
      
      return customAxios<unknown>(
      {url: `/folder/${folderId}/order`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateFolderOrderBody
    },
      );
    }
  


export const getUpdateFolderOrderMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFolderOrder>>, TError,{folderId: number;data: number[]}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateFolderOrder>>, TError,{folderId: number;data: number[]}, TContext> => {

const mutationKey = ['updateFolderOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFolderOrder>>, {folderId: number;data: number[]}> = (props) => {
          const {folderId,data} = props ?? {};

          return  updateFolderOrder(folderId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateFolderOrderMutationResult = NonNullable<Awaited<ReturnType<typeof updateFolderOrder>>>
    export type UpdateFolderOrderMutationBody = number[]
    export type UpdateFolderOrderMutationError = HTTPValidationError

    /**
 * @summary フォルダ内の画像順序を更新
 */
export const useUpdateFolderOrder = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFolderOrder>>, TError,{folderId: number;data: number[]}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFolderOrder>>,
        TError,
        {folderId: number;data: number[]},
        TContext
      > => {

      const mutationOptions = getUpdateFolderOrderMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary 既存のフォルダに画像を追加
 */
export const addImagesToFolder = (
    folderId: number,
    addImagesToFolderBody: number[],
 ) => {
      
      
      return customAxios<unknown>(
      {url: `/folder/${folderId}/add_images`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: addImagesToFolderBody
    },
      );
    }
  


export const getAddImagesToFolderMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addImagesToFolder>>, TError,{folderId: number;data: number[]}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addImagesToFolder>>, TError,{folderId: number;data: number[]}, TContext> => {

const mutationKey = ['addImagesToFolder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addImagesToFolder>>, {folderId: number;data: number[]}> = (props) => {
          const {folderId,data} = props ?? {};

          return  addImagesToFolder(folderId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddImagesToFolderMutationResult = NonNullable<Awaited<ReturnType<typeof addImagesToFolder>>>
    export type AddImagesToFolderMutationBody = number[]
    export type AddImagesToFolderMutationError = HTTPValidationError

    /**
 * @summary 既存のフォルダに画像を追加
 */
export const useAddImagesToFolder = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addImagesToFolder>>, TError,{folderId: number;data: number[]}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addImagesToFolder>>,
        TError,
        {folderId: number;data: number[]},
        TContext
      > => {

      const mutationOptions = getAddImagesToFolderMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * 翻訳済みのタグ一覧を取得するエンドポイント。

- 指定した言語（例: `"ja"` や `"en"`）に対応したタグを返します。
- 使用用途：多言語対応のフロントエンド表示など。

### クエリパラメータ:
- `language` (str): 翻訳対象の言語コード（デフォルト: `"ja"`）

### レスポンス:
- `200 OK`: 成功時に翻訳済みタグの配列を返します
- `404 Not Found`: タグが存在しない場合
- `500 Internal Server Error`: サーバ内部でエラーが発生した場合
 * @summary Fetch Translated Tags
 */
export const fetchTranslatedTags = (
    params?: FetchTranslatedTagsParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<Tag[]>(
      {url: `/tag/list`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchTranslatedTagsQueryKey = (params?: FetchTranslatedTagsParams,) => {
    return [`/tag/list`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchTranslatedTagsQueryOptions = <TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = HTTPValidationError>(params?: FetchTranslatedTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchTranslatedTagsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchTranslatedTags>>> = ({ signal }) => fetchTranslatedTags(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchTranslatedTagsQueryResult = NonNullable<Awaited<ReturnType<typeof fetchTranslatedTags>>>
export type FetchTranslatedTagsQueryError = HTTPValidationError


export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = HTTPValidationError>(
 params: undefined |  FetchTranslatedTagsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchTranslatedTags>>,
          TError,
          Awaited<ReturnType<typeof fetchTranslatedTags>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = HTTPValidationError>(
 params?: FetchTranslatedTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchTranslatedTags>>,
          TError,
          Awaited<ReturnType<typeof fetchTranslatedTags>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = HTTPValidationError>(
 params?: FetchTranslatedTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Translated Tags
 */

export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = HTTPValidationError>(
 params?: FetchTranslatedTagsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchTranslatedTagsQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * タグのお気に入りまたはセンシティブフラグをオン/オフします。

### パスパラメータ:
- `tag_id` (int): フラグを変更する対象のタグID

### リクエストボディ:
- `flag` (str): `"favorite"` もしくは `"sensitive"`
- `value` (bool): `true` でオン、`false` でオフ

### レスポンス:
- `200 OK`: 更新されたタグ情報
- `400 Bad Request`: 不正なフラグ指定
- `404 Not Found`: 指定IDのタグが存在しない
 * @summary Toggle Tag Flag
 */
export const toggleTagFlag = (
    tagId: number,
    tagFlagUpdate: TagFlagUpdate,
 ) => {
      
      
      return customAxios<Tag>(
      {url: `/tag/${tagId}/toggle_flag`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: tagFlagUpdate
    },
      );
    }
  


export const getToggleTagFlagMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleTagFlag>>, TError,{tagId: number;data: TagFlagUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof toggleTagFlag>>, TError,{tagId: number;data: TagFlagUpdate}, TContext> => {

const mutationKey = ['toggleTagFlag'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof toggleTagFlag>>, {tagId: number;data: TagFlagUpdate}> = (props) => {
          const {tagId,data} = props ?? {};

          return  toggleTagFlag(tagId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ToggleTagFlagMutationResult = NonNullable<Awaited<ReturnType<typeof toggleTagFlag>>>
    export type ToggleTagFlagMutationBody = TagFlagUpdate
    export type ToggleTagFlagMutationError = HTTPValidationError

    /**
 * @summary Toggle Tag Flag
 */
export const useToggleTagFlag = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof toggleTagFlag>>, TError,{tagId: number;data: TagFlagUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof toggleTagFlag>>,
        TError,
        {tagId: number;data: TagFlagUpdate},
        TContext
      > => {

      const mutationOptions = getToggleTagFlagMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    