/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  FetchFilteredThumnailImagesParams,
  FetchOriginalImageParams,
  HTTPValidationError,
  ItemListResponse,
  OriginalImageResponse,
  Tags
} from '.././model';

import { customAxios } from '.././custom-axios';




/**
 * @summary Fetch Folders
 */
export const fetchFoldersApiFolderListGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxios<unknown>(
      {url: `/api/folder/list`, method: 'GET', signal
    },
      );
    }
  

export const getFetchFoldersApiFolderListGetQueryKey = () => {
    return [`/api/folder/list`] as const;
    }

    
export const getFetchFoldersApiFolderListGetQueryOptions = <TData = Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchFoldersApiFolderListGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>> = ({ signal }) => fetchFoldersApiFolderListGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchFoldersApiFolderListGetQueryResult = NonNullable<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>>
export type FetchFoldersApiFolderListGetQueryError = unknown


export function useFetchFoldersApiFolderListGet<TData = Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>,
          TError,
          Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchFoldersApiFolderListGet<TData = Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>,
          TError,
          Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchFoldersApiFolderListGet<TData = Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Folders
 */

export function useFetchFoldersApiFolderListGet<TData = Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchFoldersApiFolderListGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Fetch Filtered Thumnail Images
 */
export const fetchFilteredThumnailImages = (
    params?: FetchFilteredThumnailImagesParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<ItemListResponse>(
      {url: `/item/list`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchFilteredThumnailImagesQueryKey = (params?: FetchFilteredThumnailImagesParams,) => {
    return [`/item/list`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchFilteredThumnailImagesQueryOptions = <TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchFilteredThumnailImagesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>> = ({ signal }) => fetchFilteredThumnailImages(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchFilteredThumnailImagesQueryResult = NonNullable<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>>
export type FetchFilteredThumnailImagesQueryError = HTTPValidationError


export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params: undefined |  FetchFilteredThumnailImagesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>,
          TError,
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>,
          TError,
          Awaited<ReturnType<typeof fetchFilteredThumnailImages>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Filtered Thumnail Images
 */

export function useFetchFilteredThumnailImages<TData = Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError = HTTPValidationError>(
 params?: FetchFilteredThumnailImagesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFilteredThumnailImages>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchFilteredThumnailImagesQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Fetch Original Image
 */
export const fetchOriginalImage = (
    params: FetchOriginalImageParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<OriginalImageResponse>(
      {url: `/item/original`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchOriginalImageQueryKey = (params: FetchOriginalImageParams,) => {
    return [`/item/original`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchOriginalImageQueryOptions = <TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchOriginalImageQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchOriginalImage>>> = ({ signal }) => fetchOriginalImage(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchOriginalImageQueryResult = NonNullable<Awaited<ReturnType<typeof fetchOriginalImage>>>
export type FetchOriginalImageQueryError = HTTPValidationError


export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchOriginalImage>>,
          TError,
          Awaited<ReturnType<typeof fetchOriginalImage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchOriginalImage>>,
          TError,
          Awaited<ReturnType<typeof fetchOriginalImage>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Original Image
 */

export function useFetchOriginalImage<TData = Awaited<ReturnType<typeof fetchOriginalImage>>, TError = HTTPValidationError>(
 params: FetchOriginalImageParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchOriginalImage>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchOriginalImageQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Fetch Translated Tags
 */
export const fetchTranslatedTags = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxios<Tags[]>(
      {url: `/tags/list`, method: 'GET', signal
    },
      );
    }
  

export const getFetchTranslatedTagsQueryKey = () => {
    return [`/tags/list`] as const;
    }

    
export const getFetchTranslatedTagsQueryOptions = <TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchTranslatedTagsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchTranslatedTags>>> = ({ signal }) => fetchTranslatedTags(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchTranslatedTagsQueryResult = NonNullable<Awaited<ReturnType<typeof fetchTranslatedTags>>>
export type FetchTranslatedTagsQueryError = unknown


export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchTranslatedTags>>,
          TError,
          Awaited<ReturnType<typeof fetchTranslatedTags>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchTranslatedTags>>,
          TError,
          Awaited<ReturnType<typeof fetchTranslatedTags>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Translated Tags
 */

export function useFetchTranslatedTags<TData = Awaited<ReturnType<typeof fetchTranslatedTags>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchTranslatedTags>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchTranslatedTagsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



