/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetItemsApiItemListGetParams,
  GetOriginalImageApiItemOriginalGetParams,
  HTTPValidationError,
  ItemListResponse,
  OriginalImageResponse,
  Tags
} from '.././model';

import { customAxios } from '.././custom-axios';




/**
 * @summary Fetch Folders
 */
export const fetchFoldersApiFolderListGet = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxios<unknown>(
      {url: `/api/folder/list`, method: 'GET', signal
    },
      );
    }
  

export const getFetchFoldersApiFolderListGetQueryKey = () => {
    return [`/api/folder/list`] as const;
    }

    
export const getFetchFoldersApiFolderListGetQueryOptions = <TData = Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchFoldersApiFolderListGetQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>> = ({ signal }) => fetchFoldersApiFolderListGet(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchFoldersApiFolderListGetQueryResult = NonNullable<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>>
export type FetchFoldersApiFolderListGetQueryError = unknown


export function useFetchFoldersApiFolderListGet<TData = Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>,
          TError,
          Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchFoldersApiFolderListGet<TData = Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>,
          TError,
          Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchFoldersApiFolderListGet<TData = Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Fetch Folders
 */

export function useFetchFoldersApiFolderListGet<TData = Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchFoldersApiFolderListGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchFoldersApiFolderListGetQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Items
 */
export const getItemsApiItemListGet = (
    params?: GetItemsApiItemListGetParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<ItemListResponse>(
      {url: `/api/item/list`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetItemsApiItemListGetQueryKey = (params?: GetItemsApiItemListGetParams,) => {
    return [`/api/item/list`, ...(params ? [params]: [])] as const;
    }

    
export const getGetItemsApiItemListGetQueryOptions = <TData = Awaited<ReturnType<typeof getItemsApiItemListGet>>, TError = HTTPValidationError>(params?: GetItemsApiItemListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemsApiItemListGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetItemsApiItemListGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getItemsApiItemListGet>>> = ({ signal }) => getItemsApiItemListGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getItemsApiItemListGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetItemsApiItemListGetQueryResult = NonNullable<Awaited<ReturnType<typeof getItemsApiItemListGet>>>
export type GetItemsApiItemListGetQueryError = HTTPValidationError


export function useGetItemsApiItemListGet<TData = Awaited<ReturnType<typeof getItemsApiItemListGet>>, TError = HTTPValidationError>(
 params: undefined |  GetItemsApiItemListGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemsApiItemListGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItemsApiItemListGet>>,
          TError,
          Awaited<ReturnType<typeof getItemsApiItemListGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemsApiItemListGet<TData = Awaited<ReturnType<typeof getItemsApiItemListGet>>, TError = HTTPValidationError>(
 params?: GetItemsApiItemListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemsApiItemListGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getItemsApiItemListGet>>,
          TError,
          Awaited<ReturnType<typeof getItemsApiItemListGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetItemsApiItemListGet<TData = Awaited<ReturnType<typeof getItemsApiItemListGet>>, TError = HTTPValidationError>(
 params?: GetItemsApiItemListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemsApiItemListGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Items
 */

export function useGetItemsApiItemListGet<TData = Awaited<ReturnType<typeof getItemsApiItemListGet>>, TError = HTTPValidationError>(
 params?: GetItemsApiItemListGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getItemsApiItemListGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetItemsApiItemListGetQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Original Image
 */
export const getOriginalImageApiItemOriginalGet = (
    params: GetOriginalImageApiItemOriginalGetParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<OriginalImageResponse>(
      {url: `/api/item/original`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetOriginalImageApiItemOriginalGetQueryKey = (params: GetOriginalImageApiItemOriginalGetParams,) => {
    return [`/api/item/original`, ...(params ? [params]: [])] as const;
    }

    
export const getGetOriginalImageApiItemOriginalGetQueryOptions = <TData = Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>, TError = HTTPValidationError>(params: GetOriginalImageApiItemOriginalGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOriginalImageApiItemOriginalGetQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>> = ({ signal }) => getOriginalImageApiItemOriginalGet(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOriginalImageApiItemOriginalGetQueryResult = NonNullable<Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>>
export type GetOriginalImageApiItemOriginalGetQueryError = HTTPValidationError


export function useGetOriginalImageApiItemOriginalGet<TData = Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>, TError = HTTPValidationError>(
 params: GetOriginalImageApiItemOriginalGetParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>,
          TError,
          Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOriginalImageApiItemOriginalGet<TData = Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>, TError = HTTPValidationError>(
 params: GetOriginalImageApiItemOriginalGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>,
          TError,
          Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetOriginalImageApiItemOriginalGet<TData = Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>, TError = HTTPValidationError>(
 params: GetOriginalImageApiItemOriginalGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Original Image
 */

export function useGetOriginalImageApiItemOriginalGet<TData = Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>, TError = HTTPValidationError>(
 params: GetOriginalImageApiItemOriginalGetParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getOriginalImageApiItemOriginalGet>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOriginalImageApiItemOriginalGetQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary Get Tags
 */
export const getTags = (
    
 signal?: AbortSignal
) => {
      
      
      return customAxios<Tags[]>(
      {url: `/api/tags/list`, method: 'GET', signal
    },
      );
    }
  

export const getGetTagsQueryKey = () => {
    return [`/api/tags/list`] as const;
    }

    
export const getGetTagsQueryOptions = <TData = Awaited<ReturnType<typeof getTags>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTagsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTags>>> = ({ signal }) => getTags(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTagsQueryResult = NonNullable<Awaited<ReturnType<typeof getTags>>>
export type GetTagsQueryError = unknown


export function useGetTags<TData = Awaited<ReturnType<typeof getTags>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTags>>,
          TError,
          Awaited<ReturnType<typeof getTags>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTags<TData = Awaited<ReturnType<typeof getTags>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTags>>,
          TError,
          Awaited<ReturnType<typeof getTags>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTags<TData = Awaited<ReturnType<typeof getTags>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Tags
 */

export function useGetTags<TData = Awaited<ReturnType<typeof getTags>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTags>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTagsQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



