/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ChainSimilarImagesInFolderParams,
  FetchAllFoldersParams,
  FolderCreateRequest,
  FolderInfo,
  HTTPValidationError,
  RenameFolderParams,
  ThumbnailImage
} from '.././model';

import { customAxios } from '.././custom-axios';




/**
 * @summary 全フォルダ情報を取得
 */
export const fetchAllFolders = (
    params?: FetchAllFoldersParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<FolderInfo[]>(
      {url: `/folder`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getFetchAllFoldersQueryKey = (params?: FetchAllFoldersParams,) => {
    return [`/folder`, ...(params ? [params]: [])] as const;
    }

    
export const getFetchAllFoldersQueryOptions = <TData = Awaited<ReturnType<typeof fetchAllFolders>>, TError = HTTPValidationError>(params?: FetchAllFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFetchAllFoldersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof fetchAllFolders>>> = ({ signal }) => fetchAllFolders(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FetchAllFoldersQueryResult = NonNullable<Awaited<ReturnType<typeof fetchAllFolders>>>
export type FetchAllFoldersQueryError = HTTPValidationError


export function useFetchAllFolders<TData = Awaited<ReturnType<typeof fetchAllFolders>>, TError = HTTPValidationError>(
 params: undefined |  FetchAllFoldersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchAllFolders>>,
          TError,
          Awaited<ReturnType<typeof fetchAllFolders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchAllFolders<TData = Awaited<ReturnType<typeof fetchAllFolders>>, TError = HTTPValidationError>(
 params?: FetchAllFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fetchAllFolders>>,
          TError,
          Awaited<ReturnType<typeof fetchAllFolders>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFetchAllFolders<TData = Awaited<ReturnType<typeof fetchAllFolders>>, TError = HTTPValidationError>(
 params?: FetchAllFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary 全フォルダ情報を取得
 */

export function useFetchAllFolders<TData = Awaited<ReturnType<typeof fetchAllFolders>>, TError = HTTPValidationError>(
 params?: FetchAllFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fetchAllFolders>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFetchAllFoldersQueryOptions(params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary 画像フォルダの作成とサムネイル取得
 */
export const createImageFolder = (
    folderCreateRequest: FolderCreateRequest,
 signal?: AbortSignal
) => {
      
      
      return customAxios<number>(
      {url: `/folder`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: folderCreateRequest, signal
    },
      );
    }
  


export const getCreateImageFolderMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createImageFolder>>, TError,{data: FolderCreateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createImageFolder>>, TError,{data: FolderCreateRequest}, TContext> => {

const mutationKey = ['createImageFolder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createImageFolder>>, {data: FolderCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createImageFolder(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateImageFolderMutationResult = NonNullable<Awaited<ReturnType<typeof createImageFolder>>>
    export type CreateImageFolderMutationBody = FolderCreateRequest
    export type CreateImageFolderMutationError = HTTPValidationError

    /**
 * @summary 画像フォルダの作成とサムネイル取得
 */
export const useCreateImageFolder = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createImageFolder>>, TError,{data: FolderCreateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createImageFolder>>,
        TError,
        {data: FolderCreateRequest},
        TContext
      > => {

      const mutationOptions = getCreateImageFolderMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary フォルダ内を類似度チェーンで並べ替えて返却
 */
export const chainSimilarImagesInFolder = (
    folderId: number,
    params: ChainSimilarImagesInFolderParams,
 signal?: AbortSignal
) => {
      
      
      return customAxios<ThumbnailImage[]>(
      {url: `/folder/${folderId}/similar_chain`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getChainSimilarImagesInFolderQueryKey = (folderId: number,
    params: ChainSimilarImagesInFolderParams,) => {
    return [`/folder/${folderId}/similar_chain`, ...(params ? [params]: [])] as const;
    }

    
export const getChainSimilarImagesInFolderQueryOptions = <TData = Awaited<ReturnType<typeof chainSimilarImagesInFolder>>, TError = HTTPValidationError>(folderId: number,
    params: ChainSimilarImagesInFolderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chainSimilarImagesInFolder>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getChainSimilarImagesInFolderQueryKey(folderId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof chainSimilarImagesInFolder>>> = ({ signal }) => chainSimilarImagesInFolder(folderId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(folderId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof chainSimilarImagesInFolder>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ChainSimilarImagesInFolderQueryResult = NonNullable<Awaited<ReturnType<typeof chainSimilarImagesInFolder>>>
export type ChainSimilarImagesInFolderQueryError = HTTPValidationError


export function useChainSimilarImagesInFolder<TData = Awaited<ReturnType<typeof chainSimilarImagesInFolder>>, TError = HTTPValidationError>(
 folderId: number,
    params: ChainSimilarImagesInFolderParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof chainSimilarImagesInFolder>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof chainSimilarImagesInFolder>>,
          TError,
          Awaited<ReturnType<typeof chainSimilarImagesInFolder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChainSimilarImagesInFolder<TData = Awaited<ReturnType<typeof chainSimilarImagesInFolder>>, TError = HTTPValidationError>(
 folderId: number,
    params: ChainSimilarImagesInFolderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chainSimilarImagesInFolder>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof chainSimilarImagesInFolder>>,
          TError,
          Awaited<ReturnType<typeof chainSimilarImagesInFolder>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useChainSimilarImagesInFolder<TData = Awaited<ReturnType<typeof chainSimilarImagesInFolder>>, TError = HTTPValidationError>(
 folderId: number,
    params: ChainSimilarImagesInFolderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chainSimilarImagesInFolder>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary フォルダ内を類似度チェーンで並べ替えて返却
 */

export function useChainSimilarImagesInFolder<TData = Awaited<ReturnType<typeof chainSimilarImagesInFolder>>, TError = HTTPValidationError>(
 folderId: number,
    params: ChainSimilarImagesInFolderParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof chainSimilarImagesInFolder>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getChainSimilarImagesInFolderQueryOptions(folderId,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



/**
 * @summary フォルダ内の画像順序を更新
 */
export const updateFolderOrder = (
    folderId: number,
    updateFolderOrderBody: number[],
 ) => {
      
      
      return customAxios<unknown>(
      {url: `/folder/${folderId}/order`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: updateFolderOrderBody
    },
      );
    }
  


export const getUpdateFolderOrderMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFolderOrder>>, TError,{folderId: number;data: number[]}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateFolderOrder>>, TError,{folderId: number;data: number[]}, TContext> => {

const mutationKey = ['updateFolderOrder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateFolderOrder>>, {folderId: number;data: number[]}> = (props) => {
          const {folderId,data} = props ?? {};

          return  updateFolderOrder(folderId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateFolderOrderMutationResult = NonNullable<Awaited<ReturnType<typeof updateFolderOrder>>>
    export type UpdateFolderOrderMutationBody = number[]
    export type UpdateFolderOrderMutationError = HTTPValidationError

    /**
 * @summary フォルダ内の画像順序を更新
 */
export const useUpdateFolderOrder = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateFolderOrder>>, TError,{folderId: number;data: number[]}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateFolderOrder>>,
        TError,
        {folderId: number;data: number[]},
        TContext
      > => {

      const mutationOptions = getUpdateFolderOrderMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary 既存のフォルダに画像を追加
 */
export const addImagesToFolder = (
    folderId: number,
    addImagesToFolderBody: number[],
 ) => {
      
      
      return customAxios<unknown>(
      {url: `/folder/${folderId}/add_images`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: addImagesToFolderBody
    },
      );
    }
  


export const getAddImagesToFolderMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addImagesToFolder>>, TError,{folderId: number;data: number[]}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addImagesToFolder>>, TError,{folderId: number;data: number[]}, TContext> => {

const mutationKey = ['addImagesToFolder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addImagesToFolder>>, {folderId: number;data: number[]}> = (props) => {
          const {folderId,data} = props ?? {};

          return  addImagesToFolder(folderId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddImagesToFolderMutationResult = NonNullable<Awaited<ReturnType<typeof addImagesToFolder>>>
    export type AddImagesToFolderMutationBody = number[]
    export type AddImagesToFolderMutationError = HTTPValidationError

    /**
 * @summary 既存のフォルダに画像を追加
 */
export const useAddImagesToFolder = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addImagesToFolder>>, TError,{folderId: number;data: number[]}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addImagesToFolder>>,
        TError,
        {folderId: number;data: number[]},
        TContext
      > => {

      const mutationOptions = getAddImagesToFolderMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary 既存のフォルダから画像を省く
 */
export const removeImagesFromFolder = (
    folderId: number,
    removeImagesFromFolderBody: number[],
 ) => {
      
      
      return customAxios<unknown>(
      {url: `/folder/${folderId}/remove_images`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: removeImagesFromFolderBody
    },
      );
    }
  


export const getRemoveImagesFromFolderMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeImagesFromFolder>>, TError,{folderId: number;data: number[]}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removeImagesFromFolder>>, TError,{folderId: number;data: number[]}, TContext> => {

const mutationKey = ['removeImagesFromFolder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeImagesFromFolder>>, {folderId: number;data: number[]}> = (props) => {
          const {folderId,data} = props ?? {};

          return  removeImagesFromFolder(folderId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveImagesFromFolderMutationResult = NonNullable<Awaited<ReturnType<typeof removeImagesFromFolder>>>
    export type RemoveImagesFromFolderMutationBody = number[]
    export type RemoveImagesFromFolderMutationError = HTTPValidationError

    /**
 * @summary 既存のフォルダから画像を省く
 */
export const useRemoveImagesFromFolder = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeImagesFromFolder>>, TError,{folderId: number;data: number[]}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeImagesFromFolder>>,
        TError,
        {folderId: number;data: number[]},
        TContext
      > => {

      const mutationOptions = getRemoveImagesFromFolderMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary フォルダ名を変更
 */
export const renameFolder = (
    folderId: number,
    params: RenameFolderParams,
 ) => {
      
      
      return customAxios<unknown>(
      {url: `/folder/${folderId}/rename`, method: 'PUT',
        params
    },
      );
    }
  


export const getRenameFolderMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameFolder>>, TError,{folderId: number;params: RenameFolderParams}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof renameFolder>>, TError,{folderId: number;params: RenameFolderParams}, TContext> => {

const mutationKey = ['renameFolder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renameFolder>>, {folderId: number;params: RenameFolderParams}> = (props) => {
          const {folderId,params} = props ?? {};

          return  renameFolder(folderId,params,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RenameFolderMutationResult = NonNullable<Awaited<ReturnType<typeof renameFolder>>>
    
    export type RenameFolderMutationError = HTTPValidationError

    /**
 * @summary フォルダ名を変更
 */
export const useRenameFolder = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renameFolder>>, TError,{folderId: number;params: RenameFolderParams}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renameFolder>>,
        TError,
        {folderId: number;params: RenameFolderParams},
        TContext
      > => {

      const mutationOptions = getRenameFolderMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    /**
 * @summary フォルダ削除
 */
export const deleteFolder = (
    folderId: number,
 ) => {
      
      
      return customAxios<unknown>(
      {url: `/folder/${folderId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteFolderMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFolder>>, TError,{folderId: number}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteFolder>>, TError,{folderId: number}, TContext> => {

const mutationKey = ['deleteFolder'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFolder>>, {folderId: number}> = (props) => {
          const {folderId} = props ?? {};

          return  deleteFolder(folderId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteFolderMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFolder>>>
    
    export type DeleteFolderMutationError = HTTPValidationError

    /**
 * @summary フォルダ削除
 */
export const useDeleteFolder = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteFolder>>, TError,{folderId: number}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteFolder>>,
        TError,
        {folderId: number},
        TContext
      > => {

      const mutationOptions = getDeleteFolderMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    